import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessoinWrapper from "@/components/SessoinWrapper";
import { connection } from "next/server";
import { ThemeProvider } from "@/components/modules/themeProvider";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import StoreWrapper from "@/components/StoreWrapper";
import AdminHeader from "@/components/AdminHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connection();
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <SessoinWrapper>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen scroll-smooth`}
        >
          <StoreWrapper>
            <ThemeProvider>
              <Navbar />
              <main className="flex-1 background-image">{children}</main>
              <Footer />
            </ThemeProvider>
          </StoreWrapper>
        </body>
      </SessoinWrapper>
    </html>
  );
}
